import React from "react";

import { Formik } from "formik";
export class EntryForm extends React.Component {
  render() {
    return (
      <div>
        <h3>Add A User</h3>
        <h2>User Number and entry date will be autogenerated </h2>
        <Formik initialValues={{ username: "", userphone: "" }}>
          {({ values, errors, touched, handleChange, handleBlur }) => (
            <form>
              <div className="input-row">
                <label htmlFor="name">Username :</label>
                <input
                  type="text"
                  name="name"
                  id="name"
                  placeholder="Enter your name"
                  onChange={handleChange}
                  onBlur={handleBlur}
                  value={values.username}
                />
              </div>
            </form>
          )}
        </Formik>
        <h3>usernumber {this.state.usernumber}</h3>
        <h1>Status is {this.state.progress}</h1>
      </div>
    );
  }
}
