import React from "react";

import { Formik } from "formik";
import * as Yup from "yup";

const validationSchema = Yup.object().shape();

export class EntryForm extends React.Component {
  render() {
    return (
      <div>
        <h3>Add A User</h3>
        <h2>User Number and entry date will be autogenerated </h2>
        <Formik initialValues={{ username: "", userphone: "" }}>
          {({ values, errors, touched, handleChange, handleBlur }) => (
            <form>
              <div className="input-row">
                <label htmlFor="username">Username :</label>
                <input
                  type="text"
                  name="username"
                  id="name"
                  placeholder="Enter your name"
                  onChange={handleChange}
                  onBlur={handleBlur}
                  value={values.username}
                />
              </div>
              <div className="input-row">
                <label htmlFor="usernumber">Usernumber :</label>
                <input
                  type="text"
                  name="usernumber"
                  id="number"
                  placeholder="Enter your Phone number"
                  onChange={handleChange}
                  onBlur={handleBlur}
                  value={values.usernumber}
                />
              </div>
            </form>
          )}
        </Formik>
        <h3>usernumber {"Holder"}</h3>
        <h1>Status is {"holder"}</h1>
      </div>
    );
  }
}
