import React from "react";
import {
  Form,
  Header,
  Dropdown,
  Message,
  Label,
  Select
} from "semantic-ui-react";

import { withFormik, Field } from "formik";
import * as Yup from "yup";

const validationSchema = Yup.object().shape({
  name: Yup.string()
    .min(1, "Cannot be empty")
    .max(30, "Now you are just showing off")
    .required(" Put in what your Mother named you"),
  userphone: Yup.string()

    .min(1, "Cannot be empty")
    .max(30, "You don't live  on  mars")
    .required("Need a number, don't be shy")
});

export class EntryForm extends React.Component {
  render() {
    return (
      <div>
        <h3>Add A User</h3>
        <h2>User Number and entry date will be autogenerated </h2>
        <Formik
          initialValues={{ username: "", userphone: "" }}
          validationSchema={validationSchema}
        >
          {({ values, errors, touched, handleChange, handleBlur }) => (
            <Form>
              <div className="input-row">
                <label htmlFor="username">Username :</label>
                <input
                  type="text"
                  name="username"
                  id="name"
                  placeholder="Enter your name"
                  onChange={handleChange}
                  onBlur={handleBlur}
                  value={values.username}
                />
              </div>
              <div className="input-row">
                <label htmlFor="userPhone">Phone :</label>
                <input
                  type="text"
                  name="userphone"
                  id="phone"
                  placeholder="Enter your Phone number"
                  onChange={handleChange}
                  onBlur={handleBlur}
                  value={values.userphone}
                />
              </div>
            </Form>
          )}
        </Formik>
        <h3>usernumber {"Holder"}</h3>
        <h1>Status is {"holder"}</h1>
      </div>
    );
  }
}
